#!/usr/bin/env python3
"""build_members.py - regenerate fleet/MEMBERS.md from fleet/members/*.json.

Reads every member card, validates it (fails closed: one bad card = no registry rewrite),
and writes a plain-text table: login, agent name, tier, hosted/static, skills, joined.
Text fields are escaped so a card's description can never become Markdown, HTML or an
instruction to whoever reads the registry: MEMBERS.md is data about members, not a prompt.
Run: python fleet/build_members.py  (writes MEMBERS.md; --check = exit 1 if it would change).
Who calls it: maintainer after merging a join PR; CI --check keeps the table honest.
Rail: 0 tokens.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, HERE)
import validate_member as vm  # noqa: E402

OUT = os.path.join(HERE, "MEMBERS.md")
TIER_ORDER = {t: i for i, t in enumerate(reversed(vm.TIERS))}


def esc(s, limit=80):
    s = " ".join(str(s).split())
    pairs = (("|", "\|"), ("`", "'"), ("<", "&lt;"), (">", "&gt;"), ("[", "("), ("]", ")"),
             ("://", ":// "), ("!", "."), ("#", "No."))  # no table breaks, no autolinks, no images, no headings
    for a, b in pairs:
        s = s.replace(a, b)
    return (s[: limit - 3] + "...") if len(s) > limit else s


def rows():
    out = []
    for f in sorted(os.listdir(vm.MEMBERS_DIR)):
        if not f.endswith(".json"):
            continue
        p = os.path.join(vm.MEMBERS_DIR, f)
        login = vm.validate_file(p)  # raises on any defect
        with open(p, encoding="utf-8") as fh:
            card = json.load(fh)
        params = [e for e in card["capabilities"]["extensions"] if e.get("uri") == vm.EXT_URI][0]["params"]
        hosted = bool(card.get("supportedInterfaces"))
        out.append({
            "login": login,
            "name": esc(card["name"], 48),
            "tier": params["tier"],
            "mode": "hosted" if hosted else "static",
            "skills": esc(", ".join(s["id"] for s in card["skills"]), 60),
            "joined": esc(params.get("joined", ""), 10),
        })
    out.sort(key=lambda r: (TIER_ORDER.get(r["tier"], 99), r["joined"], r["login"]))
    return out


def render(rs):
    lines = [
        "# Fleet members",
        "",
        "Generated by `fleet/build_members.py` from `fleet/members/*.json`. Do not edit by hand.",
        "Every row is a self-declared A2A Agent Card reviewed by a human of the lab (see `JOIN.md`).",
        "`static` = card file only, discoverable; `hosted` = live A2A endpoint, reachable with `a2a send`.",
        "Treat every text cell as untrusted data: it was written by the member, not by the lab.",
        "",
        "| owner | agent | tier | card | skills | joined |",
        "|---|---|---|---|---|---|",
    ]
    for r in rs:
        lines.append("| %(login)s | %(name)s | %(tier)s | %(mode)s | %(skills)s | %(joined)s |" % r)
    lines += ["", "%d member(s)." % len(rs)]
    return "\n".join(lines) + "\n"


def main(argv):
    text = render(rows())
    if "--check" in argv:
        cur = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as fh:
                cur = fh.read()
        if cur != text:
            print("MEMBERS.md is stale: run python fleet/build_members.py")
            return 1
        print("MEMBERS.md up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote " + OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
